[package]
name = "rust_cas"
version = "0.1.0"
authors = ["Carel Jonkhout <carel.jonkhout@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"